project: 
  type: website

site:
  title: "National Geographic Pristine Seas Expedition - Palau (2024)"
  site-url: https://pristineseas.org
  repo-url: https://github.com/pristine-seas/exp-PLW-2024
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "National Geographic Society (2022)"
 
  navbar: 
    #background: light
    right: 
      - sidebar:welcome
      - icon: github
        href: https://github.com/pristine-seas/exp-PLW-2024
      - icon: hdd
        href: "https://drive.google.com/drive/folders/1wFrwIccznqruKO5ViatH6onK5i0xCutd?usp=sharing"
 
  sidebar:
    - id: welcome
      title: "Menu"
      logo: ps-logo.png
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - href: index.qmd
          text: Overview
        - processing_scripts/00_Argo_track.qmd
        - processing_scripts/13_consolidate_exp_meta.qmd
        - section: "Analyses"
          contents: 
            - processing_scripts/01_fish_surveys.qmd
            - processing_scripts/02_benthos_surveys.qmd
            - processing_scripts/04_recruitment.qmd
            - processing_scripts/03_inverts_surveys.qmd
            - processing_scripts/05_clams.qmd
            - processing_scripts/06_ysi.qmd
            - processing_scripts/07_edna.qmd
            - processing_scripts/10_bruvs.qmd
            - processing_scripts/09_pelagics.qmd
            - processing_scripts/08_birds.qmd
            - processing_scripts/11_rov.qmd
            - processing_scripts/12_dscm.qmd
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

execute:
  freeze: auto
  
filters:
  - include-files.lua
  - quarto
