project: 
  type: website

site:
  title: "National Geographic Pristine Seas Expedition - Palau (2024)"
  site-url: https://pristineseas.org
  repo-url: https://github.com/pristine-seas/exp-PLW-2024
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "National Geographic Society (2022)"
 
  navbar: 
    #background: light
    right: 
      - sidebar:welcome
      - icon: github
        href: https://github.com/pristine-seas/exp-PLW-2024
 
  sidebar:
    - id: welcome
      title: "Menu"
      logo: ps-logo.png
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - index.qmd
        - processing_scripts/_Argo_track.qmd
        - processing_scripts/13_consolidate_exp_meta.qmd
        - section: "Analyses"
          contents: 
            - processing_scripts/01_fish_surveys.qmd
            - processing_scripts/02_benthos_surveys.qmd
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
