project: 
  type: website

site:
  title: "National Geographic Pristine Seas Expedition - Palau (2024)"
  site-url: https://pristineseas.org
  repo-url: https://github.com/pristine-seas/exp-PLW-2024
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "National Geographic Society (2022)"
 
  navbar: 
    #background: light
    right: 
      - sidebar:welcome
      - icon: github
        href: https://github.com/pristine-seas/exp-PLW-2024
 
  sidebar:
    - id: welcome
      title: "Menu"
      logo: ps-logo.png
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - section: "Welcome"
          contents:
            - index.md
        - section: prerequisites/index.md 
          contents:
            - prerequisites/01_Earthdata_Search.md ## tutorial 1
            - prerequisites/02_NASA_Earthdata_Authentication.ipynb ## tutorial 2
            - prerequisites/03_download.md
            
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
